### PR TITLE
Fix callback execution when request fails

### LINKED ISSUE #5: End callback is not called when there is an error on the request
If server returns 404 or another error, end callback gets ignored instead of calling it with the the provided error.

```
superagent
          .get('localhost:3000/invalid')
          .end(function (err, response){
            // Never called
          });
```

### PR DESCRIPTION
**Pull request by daf-spr**
Call end callback when there is an error

Fixes #5

### CODE REVIEW

**Comment by jpodwys** [comment]
Merged and published in NPM release `1.0.3`. Thanks for the input!

**Comment by fraczak** [comment]
I experience the problem (in a browser via browserify) on version 1.7.2 :(

**Comment by jpodwys** [comment]
Superagent made some internally breaking changes in `1.7.0` and later. Please see #32 for more information on what's being done about it. If you don't *need* anything in `1.7.0` or later, please move to `1.6.1` until a resolution is reached.

**Comment by jpodwys** [comment]
@fraczak Can you please provide more information? Were you on an older version of superagent and everything was working well until you upgraded, or did you just come across this the first time you tried to use superagent-cache?

**Comment by jpodwys** [comment]
@fraczak If you can, I'd appreciate a code demo. I'm unable to reproduce this error, even on `1.7.2`. Thanks!

**Pull request merged**
