### PR TITLE
Added forceUpdate feature and tests.

### PR DESCRIPTION
**Pull request by orhanhenrik**
Hi!
I am sorry the feature took so long. It's been ready for a while, but I have been traveling a lot and have been busy. The code for forceUpdate is pretty simple, and I think the test pretty much covers the functionality. Let me know if there is anything I should change before merging.

Thanks!

### CODE REVIEW

**Comment by jpodwys** [comment]
@orhanhenrik I apologize, I had an urgent PR I needed to merge to fix compatibility with > superagent `1.6.1`. Would you mind rebasing? If you're not able to, I can pull your code in manually, but I would rather you get contributor credit for your work.

**Comment by orhanhenrik** [comment]
Okay, I've rebased it now!

**Comment by jpodwys** [comment]
Thanks for rebasing! I'll look at the PR this week.

**Comment by jpodwys** [comment]
Published to npm in `1.4.0`.

**Pull request merged**
